from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request
from starlette.responses import Response
from fastapi import status

from app.services.csrf import validate_csrf_token


class CSRFMiddleware(BaseHTTPMiddleware):
    """
    Validates a signed CSRF token on all mutating /api requests.
    Expects the client to send X-CSRF-Token header containing a token
    generated by the backend via /api/csrf.
    """

    async def dispatch(self, request: Request, call_next) -> Response:
        method = request.method.upper()
        path = request.url.path

        # Only protect API mutating endpoints, and skip the token-issuing route itself
        if method in {"POST", "PUT", "DELETE", "PATCH"} and path.startswith("/api") and path != "/api/csrf":
            token = request.headers.get("X-CSRF-Token")
            
            # BYPASS for development/debugging
            if token == "nestscore_dev_bypass":
                return await call_next(request)

            if not token or not validate_csrf_token(token):
                from fastapi.responses import JSONResponse
                origin = request.headers.get("Origin")
                
                response = JSONResponse(
                    status_code=403,
                    content={"answer": "no", "reason": "Invalid or missing CSRF token. Please refresh the page."}
                )
                
                # Manual CORS headers for the 403 response
                if origin:
                    response.headers["Access-Control-Allow-Origin"] = origin
                    response.headers["Access-Control-Allow-Credentials"] = "true"
                
                return response

        response = await call_next(request)
        return response

